# Generated by Django 5.2.4 on 2025-07-12 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('web', 'موقع ويب'), ('mobile', 'تطبيق موبايل'), ('desktop', 'تطبيق سطح المكتب'), ('other', 'أخرى')], max_length=50)),
                ('state', models.CharField(choices=[('pending', 'قيد المراجعة'), ('inprogress', 'قسد التنفيذ'), ('completed', 'مكتمل')], max_length=50)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
