# Generated by Django 5.2.4 on 2025-07-12 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='ppt_presentation',
            field=models.BooleanField(default=False, verbose_name='هل تم تقديم عرض تقديمي؟'),
        ),
        migrations.AddField(
            model_name='project',
            name='tech_card',
            field=models.BooleanField(default=False, verbose_name='هل تم تقديم بطاقة تقنية؟'),
        ),
        migrations.AlterField(
            model_name='project',
            name='state',
            field=models.CharField(choices=[('pending', 'قيد المراجعة'), ('inprogress', 'قسد التنفيذ'), ('completed', 'مكتمل')], default='pending', max_length=50),
        ),
    ]
