# Generated by Django 5.2.4 on 2025-07-13 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_ppt_presentation_project_tech_card_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
