# Generated by Django 5.2.4 on 2025-07-16 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='state',
            field=models.CharField(choices=[('pending', 'قيد المراجعة'), ('inprogress', 'قيد التنفيذ'), ('completed', 'مكتمل')], default='pending', max_length=50),
        ),
    ]
