# Generated by Django 5.2.6 on 2025-09-08 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('web', 'موقع ويب'), ('mobile', 'تطبيق موبايل'), ('desktop', 'تطبيق سطح المكتب'), ('vedio', 'فيديو تقديمي'), ('other', 'أخرى')], max_length=50),
        ),
    ]
