# Generated by Django 5.2.4 on 2025-07-16 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_customuser_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='chat_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
